
steps:
  # Step 1: pull the container image if it is already built, if fails do not exit
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull gcr.io/$PROJECT_ID/gcpdemo:latest || exit 0'
   # Step 2: Create a docker image if none exists, esle load existing one
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gcpdemo:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gcpdemo:latest'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/gcpdemo:latest'
      - '.'
  # Step 3: Push the docker image to the run
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gcpdemo'
  # Step 4: Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gcpdemo'
      - '--image'
      - 'gcr.io/$PROJECT_ID/gcpdemo:latest'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'